# Generated by Django 3.0.5 on 2020-05-21 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0002_auto_20200521_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='blog',
            new_name='kurumsal',
        ),
    ]
