# Generated by Django 3.0.5 on 2020-05-24 02:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0004_auto_20200524_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurumsal',
            name='level',
        ),
        migrations.RemoveField(
            model_name='kurumsal',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='kurumsal',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='kurumsal',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='kurumsal',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='kurumsal',
            name='status',
            field=models.CharField(choices=[(1, 'Evet'), (0, 'Hayır')], max_length=10),
        ),
    ]
