# Generated by Django 3.0.5 on 2020-06-02 17:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0006_auto_20200525_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
