# Generated by Django 3.0.5 on 2020-06-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
