# Generated by Django 3.0.5 on 2020-06-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0011_auto_20200604_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurumsal',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
