# Generated by Django 3.0.5 on 2020-06-16 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kurumsal', '0014_auto_20200604_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurumsal',
            name='type',
            field=models.CharField(choices=[('haber', 'haber'), ('duyuru', 'duyuru'), ('etkinlik', 'etkinlik')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurumsal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
