# Generated by Django 3.0.5 on 2020-06-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0015_auto_20200616_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurumsal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kurumsal.Category'),
        ),
    ]
